<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>oposiciones</AssemblyName>
    <RootNamespace>Oposiciones.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Oposiciones.Domain\Oposiciones.Domain.csproj" />
    <ProjectReference Include="..\Oposiciones.Infrastructure\Oposiciones.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
