-- db/002_add_refresh_tokens.sql
CREATE TABLE IF NOT EXISTS RefreshTokens (
    Id SERIAL PRIMARY KEY,
    Token VARCHAR(255) NOT NULL UNIQUE,
    UsuarioId INT NOT NULL REFERENCES Usuarios(Id) ON DELETE CASCADE,
    ExpiresAt TIMESTAMP NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RevokedAt TIMESTAMP NULL
);
